export const REQUEST_POKEMONS = 'REQUEST_POKEMONS'
export const RECEIVE_POKEMONS = 'RECEIVE_POKEMONS'
export const FILTER_POKEMONS = 'FILTER_POKEMONS'
export const OPEN_CLOSE_MODAL = 'OPEN_CLOSE_MODAL'

export const SEND_POKEMON_CARD = 'SEND_POKEMON_CARD'
export const RECEIVE_POKEMON_STATS = 'RECEIVE_POKEMON_STATS'
export const POKEDEX_SCREEN = 'POKEDEX_SCREEN'
export const SET_POKEDEX_PAGE = 'SET_POKEDEX_PAGE'
